"""HTML email delivery over SMTP."""

from __future__ import annotations

import html
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import markdown2

import config

logger = logging.getLogger("blogbot")

EMAIL_STYLE = """
<style>
  body { font-family: -apple-system, Segoe UI, Arial, sans-serif; line-height: 1.6;
         color: #222; max-width: 820px; margin: 0 auto; padding: 16px; }
  table { border-collapse: collapse; margin: 12px 0; }
  th, td { border: 1px solid #ccc; padding: 6px 10px; text-align: left; }
  th { background: #f3f3f3; }
</style>
"""


def build_html(blogs: list[dict], date_str: str) -> str:
    parts = [
        "<html><head><meta charset='utf-8'>" + EMAIL_STYLE + "</head><body>",
        "<h2>📝 BlogBot — Daily Blog Posts</h2>",
        f"<p><strong>Date:</strong> {date_str}</p>",
        "<hr>",
    ]
    for number, blog in enumerate(blogs, start=1):
        body = markdown2.markdown(blog["content"], extras=["tables", "fenced-code-blocks"])
        parts.append(f"<h2>Blog {number}: {html.escape(blog['title'])}</h2>")
        parts.append(body)
        parts.append("<hr>")
    parts.append(
        '<p style="color: gray; font-size: 12px;">'
        "Automatically generated by BlogBot. "
"You can review this blog and add it to your website."
        "</p>"
    )
    parts.append("</body></html>")
    return "\n".join(parts)


def build_text(blogs: list[dict], date_str: str) -> str:
    sections = [f"BlogBot — Daily Blog Posts\nDate: {date_str}\n"]
    for number, blog in enumerate(blogs, start=1):
        sections.append(f"{'=' * 60}\nBlog {number}: {blog['title']}\n{'=' * 60}\n\n{blog['content']}\n")
    return "\n".join(sections)


def send_email(blogs: list[dict], date_str: str) -> bool:
    """Send all generated blogs in a single email. Returns True on success."""
    missing = [
        name
        for name, value in (
            ("EMAIL_FROM", config.EMAIL_FROM),
            ("EMAIL_TO", config.EMAIL_TO),
            ("EMAIL_PASSWORD", config.EMAIL_PASSWORD),
            ("SMTP_HOST", config.SMTP_HOST),
        )
        if not value
    ]
    if missing:
        logger.error("Email not sent, missing .env values: %s", ", ".join(missing))
        return False

    recipients = [addr.strip() for addr in config.EMAIL_TO.split(",") if addr.strip()]

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"BlogBot | {date_str} | {len(blogs)} {'Blog' if len(blogs) == 1 else 'Blogs'} Ready"
    msg["From"] = config.EMAIL_FROM
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(build_text(blogs, date_str), "plain", "utf-8"))
    msg.attach(MIMEText(build_html(blogs, date_str), "html", "utf-8"))

    try:
        if config.SMTP_PORT == 465:
            server = smtplib.SMTP_SSL(config.SMTP_HOST, config.SMTP_PORT, timeout=30)
        else:
            server = smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT, timeout=30)
            server.starttls()
        with server:
            server.login(config.EMAIL_FROM, config.EMAIL_PASSWORD)
            server.sendmail(config.EMAIL_FROM, recipients, msg.as_string())
    except smtplib.SMTPAuthenticationError:
        logger.error("SMTP authentication failed, check EMAIL_FROM / EMAIL_PASSWORD")
        return False
    except (smtplib.SMTPException, OSError) as exc:
        logger.error("Failed to send email: %s", exc)
        return False

    logger.info("Email sent to %s", ", ".join(recipients))
    return True
